name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write
  actions: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Validate composer.json and composer.lock
      run: cd server && composer validate
    - name: Install dependencies
      run: cd server && composer install --no-progress
    - name: Run test suite
      run: cd server && ./vendor/bin/phpunit tests
    # - name: Static analysis
    #   run: cd server && ./vendor/bin/phpstan analyse src tests


